import numpy as np
from PIL import Image
import io
import torch
import torch.nn as nn
from torchvision import transforms
from typing import Dict

class AIDetector:
    """
    Detects if an image was generated by AI (Stable Diffusion, DALL-E, Midjourney, etc.)
    Uses a CNN-based classifier trained on real vs AI-generated images.
    """
    
    def __init__(self):
        self.model = None
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ])
    
    async def load_model(self):
        """Load pre-trained AI detection model"""
        # In production, load actual trained model weights
        # For demo, create simple model architecture
        self.model = self._build_model()
        self.model.to(self.device)
        self.model.eval()
        print("✅ AI Detector model loaded")
    
    def _build_model(self):
        """Build simple CNN for AI detection"""
        # Simplified model - in production, use ResNet50 or EfficientNet
        model = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.Conv2d(128, 256, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d((1, 1)),
            nn.Flatten(),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )
        return model
    
    async def analyze(self, image_data: bytes) -> Dict:
        """
        Analyze if image is AI-generated
        
        Returns:
            dict with is_ai_generated (bool) and probability (float)
        """
        try:
            # Load image
            image = Image.open(io.BytesIO(image_data)).convert('RGB')
            
            # Preprocess
            input_tensor = self.transform(image).unsqueeze(0).to(self.device)
            
            # Inference
            with torch.no_grad():
                output = self.model(input_tensor)
                probability = output.item()
            
            # Additional heuristics
            noise_score = self._analyze_noise_patterns(image)
            frequency_score = self._analyze_frequency_domain(image)
            
            # Combine scores
            combined_probability = (probability * 0.6 + noise_score * 0.2 + frequency_score * 0.2)
            
            return {
                "is_ai_generated": combined_probability > 0.5,
                "probability": round(combined_probability, 4),
                "model_confidence": round(probability, 4),
                "noise_score": round(noise_score, 4),
                "frequency_score": round(frequency_score, 4),
                "details": {
                    "method": "cnn_classifier_plus_heuristics",
                    "model": "custom_ai_detector_v1",
                }
            }
            
        except Exception as e:
            print(f"❌ AI detection failed: {e}")
            return {
                "is_ai_generated": False,
                "probability": 0.0,
                "error": str(e)
            }
    
    def _analyze_noise_patterns(self, image: Image.Image) -> float:
        """
        Analyze noise patterns - AI images often have characteristic noise
        """
        img_array = np.array(image)
        
        # Calculate local variance in small patches
        patch_size = 8
        variances = []
        
        for i in range(0, img_array.shape[0] - patch_size, patch_size):
            for j in range(0, img_array.shape[1] - patch_size, patch_size):
                patch = img_array[i:i+patch_size, j:j+patch_size]
                variances.append(np.var(patch))
        
        # AI images tend to have more uniform noise
        variance_std = np.std(variances)
        
        # Normalize to 0-1 score
        noise_score = 1.0 - min(variance_std / 1000.0, 1.0)
        
        return noise_score
    
    def _analyze_frequency_domain(self, image: Image.Image) -> float:
        """
        Analyze frequency domain - AI images have characteristic patterns
        """
        img_array = np.array(image.convert('L'))  # Grayscale
        
        # FFT analysis
        fft = np.fft.fft2(img_array)
        fft_shift = np.fft.fftshift(fft)
        magnitude = np.abs(fft_shift)
        
        # AI images often have regular patterns in frequency domain
        center_power = np.mean(magnitude[
            magnitude.shape[0]//2-10:magnitude.shape[0]//2+10,
            magnitude.shape[1]//2-10:magnitude.shape[1]//2+10
        ])
        
        edge_power = np.mean([
            np.mean(magnitude[:10, :]),
            np.mean(magnitude[-10:, :]),
            np.mean(magnitude[:, :10]),
            np.mean(magnitude[:, -10:])
        ])
        
        # Calculate ratio
        ratio = center_power / (edge_power + 1e-10)
        
        # Normalize
        frequency_score = min(ratio / 100.0, 1.0)
        
        return frequency_score
