import numpy as np
from PIL import Image, ImageFilter
import io
from typing import Dict, Optional
import os

# Optional PyTorch imports
try:
    import torch
    import torch.nn as nn
    from torchvision import transforms
    TORCH_AVAILABLE = True
except ImportError:
    TORCH_AVAILABLE = False

class AIDetector:
    """
    Detects if an image was generated by AI (Stable Diffusion, DALL-E, Midjourney, etc.)
    Uses a CNN-based classifier trained on real vs AI-generated images.
    """
    
    def __init__(self):
        self.model = None
        self.device = None
        self.model_path = os.getenv("AI_DETECTOR_MODEL_PATH")
        self.model_weight = float(os.getenv("AI_MODEL_WEIGHT", "0.0"))
        self.model_available = False
        self.analysis_size = int(os.getenv("AI_ANALYSIS_SIZE", "512"))
        self.transform = None
        
        if TORCH_AVAILABLE:
            self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
            self.transform = transforms.Compose([
                transforms.Resize((224, 224)),
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
            ])
    
    async def load_model(self):
        """Load pre-trained AI detection model"""
        if not TORCH_AVAILABLE:
            print("✅ AI Detector running in heuristic mode (PyTorch not available)")
            return
            
        if self.model_path and os.path.exists(self.model_path):
            try:
                self.model = self._build_model()
                state_dict = torch.load(self.model_path, map_location=self.device)
                self.model.load_state_dict(state_dict)
                self.model.to(self.device)
                self.model.eval()
                self.model_available = True
                print("✅ AI Detector model loaded")
                return
            except Exception as e:
                print(f"⚠️ Failed to load AI detector model weights: {e}")

        self.model = None
        self.model_available = False
        print("✅ AI Detector running in heuristic mode")
    
    def _build_model(self):
        """Build simple CNN for AI detection"""
        if not TORCH_AVAILABLE:
            return None
            
        # Simplified model - in production, use ResNet50 or EfficientNet
        model = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.Conv2d(128, 256, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d((1, 1)),
            nn.Flatten(),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )
        return model
    
    async def analyze(self, image_data: bytes) -> Dict:
        """
        Analyze if image is AI-generated
        
        Returns:
            dict with is_ai_generated (bool) and probability (float)
        """
        try:
            # Load image
            image = Image.open(io.BytesIO(image_data)).convert('RGB')
            if max(image.size) > self.analysis_size:
                image.thumbnail((self.analysis_size, self.analysis_size), Image.Resampling.LANCZOS)

            model_probability: Optional[float] = None
            if TORCH_AVAILABLE and self.model_available and self.model is not None:
                input_tensor = self.transform(image).unsqueeze(0).to(self.device)
                with torch.no_grad():
                    output = self.model(input_tensor)
                    model_probability = float(output.item())
            
            # Additional heuristics
            noise_score = self._analyze_noise_patterns(image)
            frequency_score = self._analyze_frequency_domain(image)
            texture_score = self._analyze_texture_consistency(image)
            
            # Combine scores
            heuristic_probability = float(
                noise_score * 0.35 +
                frequency_score * 0.35 +
                texture_score * 0.30
            )

            if model_probability is None or self.model_weight <= 0:
                combined_probability = heuristic_probability
            else:
                model_weight = min(max(self.model_weight, 0.0), 1.0)
                combined_probability = float(
                    model_probability * model_weight + heuristic_probability * (1.0 - model_weight)
                )
            
            return {
                "is_ai_generated": bool(combined_probability > 0.6),
                "probability": round(float(combined_probability), 4),
                "model_confidence": round(float(model_probability), 4) if model_probability is not None else None,
                "noise_score": round(float(noise_score), 4),
                "frequency_score": round(float(frequency_score), 4),
                "texture_score": round(float(texture_score), 4),
                "details": {
                    "method": "heuristics_with_optional_model_fusion",
                    "model": "custom_ai_detector_v1" if self.model_available else "heuristic_only",
                }
            }
            
        except Exception as e:
            print(f"❌ AI detection failed: {e}")
            return {
                "is_ai_generated": False,
                "probability": 0.0,
                "error": str(e)
            }
    
    def _analyze_noise_patterns(self, image: Image.Image) -> float:
        """
        Analyze noise patterns - AI images often have characteristic noise
        """
        img_array = np.array(image.convert('L'), dtype=np.float32)

        # Residual noise approximation: high-pass filtered detail
        blur = np.array(image.convert('L').filter(ImageFilter.GaussianBlur(radius=1.2)), dtype=np.float32)
        residual = np.abs(img_array - blur)

        # Compare local variability (too-uniform residuals may indicate synthetic generation)
        block = 16
        h, w = residual.shape
        h_trim = (h // block) * block
        w_trim = (w // block) * block
        if h_trim == 0 or w_trim == 0:
            return 0.5

        grid = residual[:h_trim, :w_trim].reshape(h_trim // block, block, w_trim // block, block)
        block_std = grid.std(axis=(1, 3))
        spread = float(np.std(block_std))

        return float(np.clip(1.0 - spread / 25.0, 0.0, 1.0))
    
    def _analyze_frequency_domain(self, image: Image.Image) -> float:
        """
        Analyze frequency domain - AI images have characteristic patterns
        """
        img_array = np.array(image.convert('L'), dtype=np.float32)  # Grayscale
        
        # FFT analysis
        fft = np.fft.fft2(img_array)
        fft_shift = np.fft.fftshift(fft)
        magnitude = np.log1p(np.abs(fft_shift))
        
        # AI images often have regular patterns in frequency domain
        cx, cy = magnitude.shape[0] // 2, magnitude.shape[1] // 2
        window = max(min(magnitude.shape) // 20, 8)

        center_power = np.mean(magnitude[
            cx-window:cx+window,
            cy-window:cy+window
        ])
        
        edge = max(min(magnitude.shape) // 30, 6)
        edge_power = np.mean([
            np.mean(magnitude[:edge, :]),
            np.mean(magnitude[-edge:, :]),
            np.mean(magnitude[:, :edge]),
            np.mean(magnitude[:, -edge:])
        ])
        
        # Calculate ratio
        ratio = center_power / (edge_power + 1e-6)
        
        # Normalize
        frequency_score = float(np.clip((ratio - 1.0) / 4.0, 0.0, 1.0))
        
        return frequency_score

    def _analyze_texture_consistency(self, image: Image.Image) -> float:
        """Analyze texture entropy consistency across regions."""
        gray = np.array(image.convert('L'), dtype=np.uint8)
        block = 32
        h, w = gray.shape
        h_trim = (h // block) * block
        w_trim = (w // block) * block
        if h_trim == 0 or w_trim == 0:
            return 0.5

        patches = gray[:h_trim, :w_trim].reshape(h_trim // block, block, w_trim // block, block)
        entropies = []
        for i in range(patches.shape[0]):
            for j in range(patches.shape[2]):
                patch = patches[i, :, j, :].ravel()
                hist = np.bincount(patch, minlength=256).astype(np.float32)
                hist /= (hist.sum() + 1e-6)
                entropy = -np.sum(hist * np.log2(hist + 1e-6))
                entropies.append(entropy)

        entropy_std = float(np.std(entropies))
        return float(np.clip(1.0 - entropy_std / 2.0, 0.0, 1.0))
